# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/zed_channel_v1_0_project/zed_channel_v1_0_project.cache/wt [current_project]
set_property parent.project_path /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/zed_channel_v1_0_project/zed_channel_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel
  /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/ip_repo/hgc_zed_ip_1.0
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/zed_channel_v1_0_project/zed_channel_v1_0_project.runs/zed_channel_hgc_zed_ip_channel_0_0_synth_1/zed_channel_hgc_zed_ip_channel_0_0.dcp
set_property used_in_implementation false [get_files /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/zed_channel_v1_0_project/zed_channel_v1_0_project.runs/zed_channel_hgc_zed_ip_channel_0_0_synth_1/zed_channel_hgc_zed_ip_channel_0_0.dcp]
add_files -quiet /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/zed_channel_v1_0_project/zed_channel_v1_0_project.runs/zed_channel_selectio_wiz_0_0_synth_1/zed_channel_selectio_wiz_0_0.dcp
set_property used_in_implementation false [get_files /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/zed_channel_v1_0_project/zed_channel_v1_0_project.runs/zed_channel_selectio_wiz_0_0_synth_1/zed_channel_selectio_wiz_0_0.dcp]
add_files -quiet /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/zed_channel_v1_0_project/zed_channel_v1_0_project.runs/zed_channel_selectio_wiz_0_1_synth_1/zed_channel_selectio_wiz_0_1.dcp
set_property used_in_implementation false [get_files /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/zed_channel_v1_0_project/zed_channel_v1_0_project.runs/zed_channel_selectio_wiz_0_1_synth_1/zed_channel_selectio_wiz_0_1.dcp]
read_vhdl -library xil_defaultlib /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/hdl/zed_channel.vhd
read_xdc /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/zed_channel_ooc.xdc
set_property used_in_implementation false [get_files /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/zed_channel_ooc.xdc]

read_xdc /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/zed_channel_ooc.xdc
set_property used_in_implementation false [get_files /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/zed_channel_ooc.xdc]

synth_design -top zed_channel -part xc7z020clg484-1
write_checkpoint -noxdef zed_channel.dcp
catch { report_utilization -file zed_channel_utilization_synth.rpt -pb zed_channel_utilization_synth.pb }
