# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/top/top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top}]

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0}]

# IP: bd/top/ip/top_processing_system7_0_axi_periph_0/top_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==top_processing_system7_0_axi_periph_0}]

# IP: bd/top/ip/top_rst_processing_system7_0_100M_0/top_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==top_rst_processing_system7_0_100M_0}]

# IP: bd/top/ip/top_zed_channel_0_0/top_zed_channel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_zed_channel_0_0 || ORIG_REF_NAME==top_zed_channel_0_0}]

# IP: bd/top/ip/top_zed_channel_0_0/ip/zed_channel_hgc_zed_ip_channel_0_0/zed_channel_hgc_zed_ip_channel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_channel_hgc_zed_ip_channel_0_0 || ORIG_REF_NAME==zed_channel_hgc_zed_ip_channel_0_0}]

# IP: bd/top/ip/top_zed_channel_0_0/ip/zed_channel_hgc_zed_ip_channel_0_0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/ip/tdpram_32x256/tdpram_32x256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tdpram_32x256 || ORIG_REF_NAME==tdpram_32x256}]

# IP: bd/top/ip/top_zed_channel_0_0/ip/zed_channel_selectio_wiz_0_0/zed_channel_selectio_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_channel_selectio_wiz_0_0 || ORIG_REF_NAME==zed_channel_selectio_wiz_0_0}]

# IP: bd/top/ip/top_zed_channel_0_0/ip/zed_channel_selectio_wiz_0_1/zed_channel_selectio_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_channel_selectio_wiz_0_1 || ORIG_REF_NAME==zed_channel_selectio_wiz_0_1}]

# IP: bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_clk_wiz_0_0 || ORIG_REF_NAME==top_clk_wiz_0_0}]

# IP: bd/top/ip/top_hgc_zed_common_0_0/top_hgc_zed_common_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_hgc_zed_common_0_0 || ORIG_REF_NAME==top_hgc_zed_common_0_0}]

# IP: bd/top/ip/top_auto_pc_0/top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_auto_pc_0 || ORIG_REF_NAME==top_auto_pc_0}]

# XDC: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/top/ip/top_rst_processing_system7_0_100M_0/top_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==top_rst_processing_system7_0_100M_0}]

# XDC: bd/top/ip/top_rst_processing_system7_0_100M_0/top_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==top_rst_processing_system7_0_100M_0}]

# XDC: bd/top/ip/top_rst_processing_system7_0_100M_0/top_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/top/ip/top_zed_channel_0_0/ip/zed_channel_hgc_zed_ip_channel_0_0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/ip/tdpram_32x256/tdpram_32x256_ooc.xdc

# XDC: bd/top/ip/top_zed_channel_0_0/ip/zed_channel_hgc_zed_ip_channel_0_0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/constrs_1/new/hgc_zed_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zed_channel_hgc_zed_ip_channel_0_0 || ORIG_REF_NAME==zed_channel_hgc_zed_ip_channel_0_0}] {/U0 }]/U0 ]]

# XDC: bd/top/ip/top_zed_channel_0_0/ip/zed_channel_selectio_wiz_0_0/zed_channel_selectio_wiz_0_0_ooc.xdc

# XDC: bd/top/ip/top_zed_channel_0_0/ip/zed_channel_selectio_wiz_0_0/zed_channel_selectio_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zed_channel_selectio_wiz_0_0 || ORIG_REF_NAME==zed_channel_selectio_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/top/ip/top_zed_channel_0_0/ip/zed_channel_selectio_wiz_0_1/zed_channel_selectio_wiz_0_1_ooc.xdc

# XDC: bd/top/ip/top_zed_channel_0_0/ip/zed_channel_selectio_wiz_0_1/zed_channel_selectio_wiz_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zed_channel_selectio_wiz_0_1 || ORIG_REF_NAME==zed_channel_selectio_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/top/ip/top_zed_channel_0_0/zed_channel_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_zed_channel_0_0 || ORIG_REF_NAME==top_zed_channel_0_0}] {/U0 }]/U0 ]]

# XDC: bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_clk_wiz_0_0 || ORIG_REF_NAME==top_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_clk_wiz_0_0 || ORIG_REF_NAME==top_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0_ooc.xdc

# XDC: bd/top/ip/top_auto_pc_0/top_auto_pc_0_ooc.xdc

# XDC: bd/top/top_ooc.xdc
