# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_hgc_zed_ip_channel_0_0/zed_channel_hgc_zed_ip_channel_0_0.xci
# IP: The module: 'zed_channel_hgc_zed_ip_channel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_hgc_zed_ip_channel_0_0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/ip/tdpram_32x256/tdpram_32x256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tdpram_32x256 || ORIG_REF_NAME==tdpram_32x256}]

# XDC: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_hgc_zed_ip_channel_0_0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/ip/tdpram_32x256/tdpram_32x256_ooc.xdc

# XDC: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_hgc_zed_ip_channel_0_0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/constrs_1/new/hgc_zed_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_channel_hgc_zed_ip_channel_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_hgc_zed_ip_channel_0_0/zed_channel_hgc_zed_ip_channel_0_0.xci
# IP: The module: 'zed_channel_hgc_zed_ip_channel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_hgc_zed_ip_channel_0_0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/ip/tdpram_32x256/tdpram_32x256.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tdpram_32x256 || ORIG_REF_NAME==tdpram_32x256}]

# XDC: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_hgc_zed_ip_channel_0_0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/ip/tdpram_32x256/tdpram_32x256_ooc.xdc

# XDC: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_hgc_zed_ip_channel_0_0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/constrs_1/new/hgc_zed_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_channel_hgc_zed_ip_channel_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
