# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_selectio_wiz_0_0/zed_channel_selectio_wiz_0_0.xci
# IP: The module: 'zed_channel_selectio_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_selectio_wiz_0_0/zed_channel_selectio_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_channel_selectio_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_selectio_wiz_0_0/zed_channel_selectio_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_channel_selectio_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_selectio_wiz_0_0/zed_channel_selectio_wiz_0_0.xci
# IP: The module: 'zed_channel_selectio_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_selectio_wiz_0_0/zed_channel_selectio_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_channel_selectio_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/jlow/Work/Vivado/testbeam_7a/HGC_ZED_0/hgc_zed/hgc_zed.srcs/sources_1/bd/zed_channel/ip/zed_channel_selectio_wiz_0_0/zed_channel_selectio_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_channel_selectio_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
