######################################################################
##
## Filename: hgc_zed_channel_tb.do
## Created on: Tue Jan 26 08:34:58 2016
##
##  Auto generated by Vivado for Behavioral Simulation
##
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##  You may want to add additional commands to control the simulation
##  in the user specific do file (<module>.udo) which is automatically
##  generated in the simulation directory and will not be removed on
##  subsequent simulation flow runs from Vivado.
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##
######################################################################
#

#
# Create work library
#
vlib work
vlib msim/blk_mem_gen_v8_2
vlib msim/xil_defaultlib

#
# Map libraries
#
vmap blk_mem_gen_v8_2 msim/blk_mem_gen_v8_2
vmap xil_defaultlib msim/xil_defaultlib

#
# Design sources
#
vlog  -incr  -work blk_mem_gen_v8_2  "c:/CMS_HGC/HGC_ZED/ip_repo/hgc_zed_ip_1.0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/ip/tdpram_32x256/blk_mem_gen_v8_2/simulation/blk_mem_gen_v8_2.v"
vlog  -incr  -work xil_defaultlib  "c:/CMS_HGC/HGC_ZED/ip_repo/hgc_zed_ip_1.0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/ip/tdpram_32x256/sim/tdpram_32x256.v"
vcom  -work xil_defaultlib -93 "C:/CMS_HGC/HGC_ZED/ip_repo/hgc_zed_ip_1.0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/new/ctrl_send_mem.vhd"
vcom  -work xil_defaultlib -93 "C:/CMS_HGC/HGC_ZED/ip_repo/hgc_zed_ip_1.0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/new/ctrl_rcv_mem.vhd"
vcom  -work xil_defaultlib -93 "C:/CMS_HGC/HGC_ZED/ip_repo/hgc_zed_ip_1.0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/new/MasterFSM.vhd"
vcom  -work xil_defaultlib -93 "C:/CMS_HGC/HGC_ZED/ip_repo/hgc_zed_ip_1.0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/new/hgc_zed_channel.vhd"
vcom  -work xil_defaultlib -93 "C:/CMS_HGC/HGC_ZED/ip_repo/hgc_zed_ip_1.0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/new/mdec_nibble.vhd"
vcom  -work xil_defaultlib -93 "C:/CMS_HGC/HGC_ZED/ip_repo/hgc_zed_ip_1.0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/new/menc_nibble.vhd"
vcom  -work xil_defaultlib -93 "C:/CMS_HGC/HGC_ZED/ip_repo/hgc_zed_ip_1.0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/new/align_deser_data.vhd"
vcom  -work xil_defaultlib -93 "C:/CMS_HGC/HGC_ZED/ip_repo/hgc_zed_ip_1.0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.srcs/sources_1/new/hgc_pck.vhd"
vcom  -work xil_defaultlib -93 "C:/CMS_HGC/HGC_ZED/ip_repo/hgc_zed_ip_1.0/hgc_zed_ip_v1_0_project/hgc_zed_ip_v1_0_project.sim/sim_1/behav/hgc_zed_channel_tb.vhd"

#
# Add global set/reset
#
vlog -work xil_defaultlib "C:/Xilinx/Vivado/2014.2/data/verilog/src/glbl.v"

#
# Call vsim to invoke simulator
#
vsim -voptargs="+acc" -t 1ps -L unisims_ver -L unimacro_ver -L secureip -L blk_mem_gen_v8_2 -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.hgc_zed_channel_tb xil_defaultlib.glbl

#
# Source wave do file
#
do {hgc_zed_channel_tb_wave.do}

#
# Set the window types
#
view wave
view structure
view signals

#
# Source user do file (UDO)
#
do {hgc_zed_channel_tb.udo}

#
# Run simulation for this time
#
run 10000ns


#
# End
#
