######################################################################
##
## Filename: hgc_zed_channel_tb.udo
## Created on: Mon Jan 11 10:49:01 2016
##
##  Auto generated by Vivado for Behavioral Simulation
##
##  You may want to edit this file to control the simulation
##
######################################################################
